name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-consumer:
    runs-on: ubuntu-latest
    name: Test Poke API Consumer

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies for poke-api-consumer
      run: |
        cd poke-api-consumer
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests for poke-api-consumer
      run: |
        cd poke-api-consumer
        pytest

  test-producer:
    runs-on: ubuntu-latest
    name: Test Poke API Producer

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies for poke-api-producer
      run: |
        cd poke-api-producer
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests for poke-api-producer
      run: |
        cd poke-api-producer
        pytest
